name: pacman
version: 0.1.0.0
github: "borillo/pacman"
license: BSD3
author: "Ricardo Borillo"
maintainer: "borillo@gmail.com"
copyright: "MIT"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/borillo/pacman#readme>

dependencies:
  - base >= 4.7 && < 5
  - brick
  - vty
  - lens
  - containers
  - mtl

library:
  source-dirs: src

executables:
  pacman-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - pacman

tests:
  pacman-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - pacman
